#pragma once
#define CONFIG_ENC_MPD_PORT 16600
#define CONFIG_ENC_I2S_BCLK_GPIO 3
#define CONFIG_ENC_I2S_WS_GPIO 1
#define CONFIG_ENC_I2S_DOUT_GPIO 9
#ifndef CONFIG_ENC_RESUME_TIMEOUT_S
#define CONFIG_ENC_RESUME_TIMEOUT_S 600
#endif
